name: superuser_demo
description: "Flutter superuser package demo application"
publish_to: 'none'
version: 2.1.0
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  superuser:
    git:
      url: https://github.com/rk0cc/superuser.git
      path: superuser/
      ref: main
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
#dependency_overrides:
#  superuser:
#    path: ../superuser/superuser/
#  superuser_plugin_unix:
#    path: ../superuser/superuser_plugin_unix/
#  superuser_plugin_windows:
#    path: ../superuser/superuser_plugin_windows/
flutter:
  uses-material-design: true
